name: Hello Github Actions

on: push

jobs: 
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub actions"

      - name: Show Date
        run: date

      - name: System Informartion
        run: |
         echo "Operating System:"
         uname -a
         echo "Current User:"
         whoami
      - name: Run Test
        run: 
         echo "Running test..."
         test 10 -eq 2038
         echo "Test Passed"
